In [6]:
import datetime
import logging
import pathlib

import polars as pl
from memory_profiler import profile
from polars import Schema
from polars.datatypes import (
    Boolean,
    Float64,
    Int64,
    List,
    String,
    Struct,
)

ROOT_DIR_PATH = pathlib.Path(".").resolve().parent
DATA_DIR_PATH = ROOT_DIR_PATH / "data"
FAKE_GAMING_DATA_DIR = DATA_DIR_PATH / "fake_gaming_data"

## Define Schema

In [7]:
schema = Schema(
    {
        "team_id": String,
        "name": String,
        "created_date": String,
        "ranking": Int64,
        "total_winnings": Int64,
        "members": List(
            Struct(
                {
                    "player_id": String,
                    "username": String,
                    "account_details": Struct(
                        {
                            "email": String,
                            "registration_date": String,
                            "premium_status": Boolean,
                            "country": String,
                            "language": String,
                        }
                    ),
                    "stats": Struct(
                        {
                            "level": Int64,
                            "experience": Int64,
                            "total_matches": Int64,
                            "win_rate": Float64,
                            "playtime_hours": Int64,
                            "achievements_completed": Int64,
                        }
                    ),
                    "inventory": Struct(
                        {
                            "currency": Struct({"premium": Int64, "standard": Int64}),
                            "items": List(
                                Struct(
                                    {
                                        "item_id": String,
                                        "name": String,
                                        "type": String,
                                        "rarity": String,
                                        "level_requirement": Int64,
                                        "stats": Struct(
                                            {
                                                "attack": Int64,
                                                "defense": Int64,
                                                "magic": Int64,
                                                "speed": Int64,
                                            }
                                        ),
                                    }
                                )
                            ),
                        }
                    ),
                    "achievements": List(
                        Struct(
                            {
                                "id": String,
                                "name": String,
                                "difficulty": String,
                                "completion_rate": Float64,
                                "points": Int64,
                                "date": String,
                            }
                        )
                    ),
                    "recent_matches": List(
                        Struct(
                            {
                                "match_id": String,
                                "game_mode": String,
                                "map": String,
                                "duration_minutes": Int64,
                                "date": String,
                                "stats": Struct(
                                    {
                                        "kills": Int64,
                                        "deaths": Int64,
                                        "assists": Int64,
                                        "damage_dealt": Int64,
                                        "healing_done": Int64,
                                        "accuracy": Float64,
                                        "headshot_percentage": Float64,
                                        "objectives_completed": Int64,
                                    }
                                ),
                                "rewards": Struct(
                                    {
                                        "experience": Int64,
                                        "currency": Int64,
                                        "items_dropped": List(
                                            Struct(
                                                {
                                                    "item_id": String,
                                                    "name": String,
                                                    "rarity": String,
                                                    "value": Int64,
                                                }
                                            )
                                        ),
                                    }
                                ),
                            }
                        )
                    ),
                }
            )
        ),
        "tournament_history": List(
            Struct(
                {
                    "tournament_id": String,
                    "name": String,
                    "placement": Int64,
                    "prize_money": Int64,
                    "matches_played": Int64,
                }
            )
        ),
    }
)

## Read LazyFrame 
(No execution triggered, data is loaded lazily aka. dag generation, like in spark)

In [8]:
lf: pl.LazyFrame = pl.scan_ndjson(
    FAKE_GAMING_DATA_DIR / "data.json",
    schema=schema,
)

In [9]:
lf.explain(optimized=True)

'NDJson SCAN [/Users/jakubpluta/Repositories/priv/polars-internals/data/fake_gaming_data/data.json]\nPROJECT */7 COLUMNS'

In [10]:
sample = lf.limit(5).collect(
    streaming=True
)  # read only 5 records. LazyFrame materialized into DataFrame

In [11]:
sample.head(1)

shape: (1, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ list[struct[ ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆ 7]]          ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ [{"f16ba9c0- ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ f9ea-4079-b2 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 06-a8e…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [12]:
sample.schema

Schema([('team_id', String),
        ('name', String),
        ('created_date', String),
        ('ranking', Int64),
        ('total_winnings', Int64),
        ('members',
         List(Struct({'player_id': String, 'username': String, 'account_details': Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}), 'stats': Struct({'level': Int64, 'experience': Int64, 'total_matches': Int64, 'win_rate': Float64, 'playtime_hours': Int64, 'achievements_completed': Int64}), 'inventory': Struct({'currency': Struct({'premium': Int64, 'standard': Int64}), 'items': List(Struct({'item_id': String, 'name': String, 'type': String, 'rarity': String, 'level_requirement': Int64, 'stats': Struct({'attack': Int64, 'defense': Int64, 'magic': Int64, 'speed': Int64})}))}), 'achievements': List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})), 'recent_matches': List(Struct({'match_id': String, 'game_mode': String, 'map': String, 'duration_minutes': Int64, 'date': String, 'stats': Struct({'kills': Int64, 'deaths': Int64, 'assists': Int64, 'damage_dealt': Int64, 'healing_done': Int64, 'accuracy': Float64, 'headshot_percentage': Float64, 'objectives_completed': Int64}), 'rewards': Struct({'experience': Int64, 'currency': Int64, 'items_dropped': List(Struct({'item_id': String, 'name': String, 'rarity': String, 'value': Int64}))})}))}))),
        ('tournament_history',
         List(Struct({'tournament_id': String, 'name': String, 'placement': Int64, 'prize_money': Int64, 'matches_played': Int64})))])

In [13]:
sample.dtypes

[String,
 String,
 String,
 Int64,
 Int64,
 List(Struct({'player_id': String, 'username': String, 'account_details': Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}), 'stats': Struct({'level': Int64, 'experience': Int64, 'total_matches': Int64, 'win_rate': Float64, 'playtime_hours': Int64, 'achievements_completed': Int64}), 'inventory': Struct({'currency': Struct({'premium': Int64, 'standard': Int64}), 'items': List(Struct({'item_id': String, 'name': String, 'type': String, 'rarity': String, 'level_requirement': Int64, 'stats': Struct({'attack': Int64, 'defense': Int64, 'magic': Int64, 'speed': Int64})}))}), 'achievements': List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})), 'recent_matches': List(Struct({'match_id': String, 'game_mode': String, 'map': String, 'duration_minutes': Int64, 'date': String, 'stats': Struct({'kills': Int64, 'deaths': Int64, 'assists': Int64, 'damage_dealt': Int64, 'healing_done': Int64, 'accuracy': Float64, 'headshot_percentage': Float64, 'objectives_completed': Int64}), 'rewards': Struct({'experience': Int64, 'currency': Int64, 'items_dropped': List(Struct({'item_id': String, 'name': String, 'rarity': String, 'value': Int64}))})}))})),
 List(Struct({'tournament_id': String, 'name': String, 'placement': Int64, 'prize_money': Int64, 'matches_played': Int64}))]

In [14]:
df = lf.collect()  # load whole data into memory

In [15]:
df.shape  # 14701 records, 7 columns

(14701, 7)

In [16]:
df.head(1)

shape: (1, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ list[struct[ ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆ 7]]          ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ [{"f16ba9c0- ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ f9ea-4079-b2 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 06-a8e…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [17]:
### members, tournament_history  is a list of structs, we can explode them into multi rows

In [18]:
df_members_exploded = df.explode(pl.col("members"))

In [19]:
df_members_exploded.head()

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ struct[7]    ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆              ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"f16ba9c0-f ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 9ea-4079-b20 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 6-a8e0…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"f3c264e6-6 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ b6c-4542-a13 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 3-380b…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"3ca0008c-f ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 50c-4afa-81d ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 4-86fb…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"dc4b5442-2 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ daf-452b-8de ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 9-7e21…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"b81d68ff-4 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 1dd-4532-9b8 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 0-98bd…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [20]:
df_members_exploded.shape  # we exploded from 14701 -> 110613 records

(110613, 7)

In [21]:
### We can also spread (unnest) struct into multiple columns

In [22]:
df_members_exploded_spread = df_members_exploded.unnest("members")

In [23]:
df_members_exploded_spread.head(1)

shape: (1, 13)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ team_id    ┆ name      ┆ created_d ┆ ranking ┆ … ┆ inventory ┆ achieveme ┆ recent_ma ┆ tournamen │
│ ---        ┆ ---       ┆ ate       ┆ ---     ┆   ┆ ---       ┆ nts       ┆ tches     ┆ t_history │
│ str        ┆ str       ┆ ---       ┆ i64     ┆   ┆ struct[2] ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆ str       ┆         ┆   ┆           ┆ list[stru ┆ list[stru ┆ list[stru │
│            ┆           ┆           ┆         ┆   ┆           ┆ ct[6]]    ┆ ct[7]]    ┆ ct[5]]    │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3d11adbe-3 ┆ Squad     ┆ 2024-11-2 ┆ 493     ┆ … ┆ {{5067,85 ┆ [{"5695d5 ┆ [{"7f06e1 ┆ [{"33b25f │
│ 6d0-4af4-9 ┆ Johnson   ┆ 2         ┆         ┆   ┆ 179},[{"9 ┆ 38-f8c2-4 ┆ 44-0d2c-4 ┆ 51-088d-4 │
│ ac1-194ef7 ┆ Inc       ┆           ┆         ┆   ┆ 0f6348c-3 ┆ 62e-b90b- ┆ 39f-9c98- ┆ 014-8e23- │
│ …          ┆           ┆           ┆         ┆   ┆ f55…      ┆ 269…      ┆ 7a0…      ┆ 06f…      │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [24]:
df_members_exploded_spread.shape

(110613, 13)

In [25]:
### we can now access elements from structs

In [26]:
df_members_exploded_spread.select("account_details").schema

Schema([('account_details',
         Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}))])

In [27]:
# extract 2 fileds from struct
df_members_exploded_spread.select(
    pl.col("account_details").struct["country"],
    pl.col("account_details").struct["premium_status"],
)

shape: (110_613, 2)
┌─────────────────────────────────┬────────────────┐
│ country                         ┆ premium_status │
│ ---                             ┆ ---            │
│ str                             ┆ bool           │
╞═════════════════════════════════╪════════════════╡
│ Gibraltar                       ┆ true           │
│ Romania                         ┆ true           │
│ Egypt                           ┆ true           │
│ Malta                           ┆ false          │
│ Antarctica (the territory Sout… ┆ true           │
│ …                               ┆ …              │
│ Mali                            ┆ false          │
│ New Zealand                     ┆ true           │
│ Burundi                         ┆ false          │
│ United States Minor Outlying I… ┆ false          │
│ Cote d'Ivoire                   ┆ true           │
└─────────────────────────────────┴────────────────┘

In [28]:
# extract filed from list
df_members_exploded_spread.select("achievements").schema

Schema([('achievements',
         List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})))])

In [29]:
df_members_exploded_spread.select("achievements").head(1)

shape: (1, 1)
┌─────────────────────────────────┐
│ achievements                    │
│ ---                             │
│ list[struct[6]]                 │
╞═════════════════════════════════╡
│ [{"5695d538-f8c2-462e-b90b-269… │
└─────────────────────────────────┘

In [30]:
df_members_exploded_spread.select(pl.col("achievements").list.get(0)).head(
    1
)  # first element from list

shape: (1, 1)
┌─────────────────────────────────┐
│ achievements                    │
│ ---                             │
│ struct[6]                       │
╞═════════════════════════════════╡
│ {"5695d538-f8c2-462e-b90b-269c… │
└─────────────────────────────────┘

In [31]:
df_members_exploded_spread.select(
    pl.col("achievements").list.eval(pl.element().struct["points"])
)  # extract field from list of structs

shape: (110_613, 1)
┌───────────────────┐
│ achievements      │
│ ---               │
│ list[i64]         │
╞═══════════════════╡
│ [662, 847, … 729] │
│ [695, 559, … 562] │
│ [339, 179, … 370] │
│ [462, 52, … 780]  │
│ [293, 23, … 218]  │
│ …                 │
│ [525, 107, … 871] │
│ [513, 863, … 736] │
│ [525, 681, … 410] │
│ [630, 556, … 867] │
│ [145, 264, … 595] │
└───────────────────┘

In [32]:
df_members_exploded_spread.select(
    pl.col("achievements").list.eval(pl.element().struct["points"]).list.mean()
)  # calculate mean points

shape: (110_613, 1)
┌──────────────┐
│ achievements │
│ ---          │
│ f64          │
╞══════════════╡
│ 490.875      │
│ 544.090909   │
│ 461.222222   │
│ 442.25       │
│ 435.833333   │
│ …            │
│ 502.0        │
│ 578.75       │
│ 656.5        │
│ 658.375      │
│ 491.785714   │
└──────────────┘

In [33]:
df_members_exploded_spread.select(pl.col("achievements")).explode(
    pl.col("achievements")
).unnest("achievements")

shape: (1_383_216, 6)
┌──────────────────────┬──────────────────────┬────────────┬─────────────────┬────────┬────────────┐
│ id                   ┆ name                 ┆ difficulty ┆ completion_rate ┆ points ┆ date       │
│ ---                  ┆ ---                  ┆ ---        ┆ ---             ┆ ---    ┆ ---        │
│ str                  ┆ str                  ┆ str        ┆ f64             ┆ i64    ┆ str        │
╞══════════════════════╪══════════════════════╪════════════╪═════════════════╪════════╪════════════╡
│ 5695d538-f8c2-462e-b ┆ Ultimate Boss Slayer ┆ Extreme    ┆ 45.57           ┆ 662    ┆ 2024-12-28 │
│ 90b-269c93…          ┆                      ┆            ┆                 ┆        ┆            │
│ 59e568e5-4f56-492d-8 ┆ 100% Completion      ┆ Medium     ┆ 24.42           ┆ 847    ┆ 2025-01-13 │
│ e21-100193…          ┆                      ┆            ┆                 ┆        ┆            │
│ c26f4010-0162-4e96-9 ┆ Speed Runner         ┆ Extreme    ┆ 56.01           ┆ 109    ┆ 2025-01-09 │
│ 497-d0f651…          ┆                      ┆            ┆                 ┆        ┆            │
│ c187c0e0-231f-4ef4-b ┆ Master of Combat     ┆ Extreme    ┆ 31.29           ┆ 836    ┆ 2024-11-14 │
│ 5c3-2e9216…          ┆                      ┆            ┆                 ┆        ┆            │
│ 451377a4-498b-4fbc-8 ┆ Speed Runner         ┆ Hard       ┆ 97.69           ┆ 277    ┆ 2025-01-04 │
│ 405-82f4d3…          ┆                      ┆            ┆                 ┆        ┆            │
│ …                    ┆ …                    ┆ …          ┆ …               ┆ …      ┆ …          │
│ 821baf37-9aee-481f-9 ┆ 100% Completion      ┆ Hard       ┆ 82.26           ┆ 755    ┆ 2024-12-19 │
│ b6f-c17456…          ┆                      ┆            ┆                 ┆        ┆            │
│ d1fd0e35-69b3-4457-8 ┆ Speed Runner         ┆ Medium     ┆ 57.41           ┆ 47     ┆ 2024-12-31 │
│ 57d-5cecc7…          ┆                      ┆            ┆                 ┆        ┆            │
│ d409dce4-439c-4e6c-b ┆ Master of Combat     ┆ Easy       ┆ 94.94           ┆ 650    ┆ 2024-12-25 │
│ bfb-3fec15…          ┆                      ┆            ┆                 ┆        ┆            │
│ 737316ab-866d-41ae-b ┆ Hidden Treasure      ┆ Medium     ┆ 24.04           ┆ 998    ┆ 2024-12-27 │
│ 8ee-7ad35b…          ┆                      ┆            ┆                 ┆        ┆            │
│ 3d7e6d0d-84e7-4c4d-b ┆ Master of Combat     ┆ Easy       ┆ 32.21           ┆ 595    ┆ 2025-01-25 │
│ 871-f5aaa6…          ┆                      ┆            ┆                 ┆        ┆            │
└──────────────────────┴──────────────────────┴────────────┴─────────────────┴────────┴────────────┘

In [36]:
df_members_exploded_spread.select("team_id", "player_id", "achievements").explode(
    pl.col("achievements")
).unnest("achievements").group_by("team_id", "player_id").agg(
    pl.col("completion_rate").mean().alias("avg_player_completion_rate"),
    pl.col("points").mean().alias("avg_player_points"),
)

shape: (110_613, 4)
┌──────────────────────────┬─────────────────────────┬─────────────────────────┬───────────────────┐
│ team_id                  ┆ player_id               ┆ avg_player_completion_r ┆ avg_player_points │
│ ---                      ┆ ---                     ┆ ate                     ┆ ---               │
│ str                      ┆ str                     ┆ ---                     ┆ f64               │
│                          ┆                         ┆ f64                     ┆                   │
╞══════════════════════════╪═════════════════════════╪═════════════════════════╪═══════════════════╡
│ a59d2a26-9825-4391-a896- ┆ ba162c51-31eb-461b-a3f0 ┆ 46.466                  ┆ 558.1             │
│ a4bfbe…                  ┆ -cb3405…                ┆                         ┆                   │
│ cb7156bf-2ca8-400f-b23e- ┆ 580e8f10-f3be-4ec4-8cd4 ┆ 52.85                   ┆ 613.333333        │
│ 7a019c…                  ┆ -abd1a2…                ┆                         ┆                   │
│ 015c5d16-ddb8-41c0-914c- ┆ b42364ea-2cec-4ddc-8058 ┆ 55.958                  ┆ 295.2             │
│ 986bcd…                  ┆ -e1fa7d…                ┆                         ┆                   │
│ 78a8d714-e3dc-4014-a03d- ┆ fa2b1651-1c14-4b1e-93cf ┆ 54.9625                 ┆ 443.75            │
│ 4974a9…                  ┆ -ce9397…                ┆                         ┆                   │
│ 867996a2-e6ca-4c4b-a4e4- ┆ 627e3c7f-ba2b-44d8-9127 ┆ 30.14625                ┆ 580.75            │
│ 449c6a…                  ┆ -e1450f…                ┆                         ┆                   │
│ …                        ┆ …                       ┆ …                       ┆ …                 │
│ 0da33d28-82c1-44d9-8d19- ┆ 584ef26a-4f69-45c3-8891 ┆ 37.384444               ┆ 605.111111        │
│ d2573d…                  ┆ -9cf455…                ┆                         ┆                   │
│ e6ad3da1-8f69-4598-a081- ┆ 38ae3fb0-ee82-4372-8a7d ┆ 48.0                    ┆ 490.428571        │
│ a31886…                  ┆ -83dc46…                ┆                         ┆                   │
│ c8a9785c-1514-4b0f-aa84- ┆ 8cbf0705-4822-484d-a516 ┆ 44.053529               ┆ 456.647059        │
│ 0ac56d…                  ┆ -934519…                ┆                         ┆                   │
│ d912e323-981b-4903-afc2- ┆ 934fe253-ea10-4d5b-8d56 ┆ 57.716                  ┆ 468.6             │
│ 49b29d…                  ┆ -309621…                ┆                         ┆                   │
│ dbcd97fc-9f2f-43c8-8e84- ┆ 1e9d9b35-5bfa-4138-b1b1 ┆ 52.166429               ┆ 421.071429        │
│ 7b66a9…                  ┆ -d0f647…                ┆                         ┆                   │
└──────────────────────────┴─────────────────────────┴─────────────────────────┴───────────────────┘