In [32]:
import datetime
import logging
import pathlib

import polars as pl
from memory_profiler import profile
from polars import Schema
from polars.datatypes import (
    Boolean,
    Float64,
    Int64,
    List,
    String,
    Struct,
)
import polars.selectors as cs

ROOT_DIR_PATH = pathlib.Path(".").resolve().parent
DATA_DIR_PATH = ROOT_DIR_PATH / "data"
FAKE_GAMING_DATA_DIR = DATA_DIR_PATH / "fake_gaming_data"

## Define Schema

In [4]:
schema = Schema(
    {
        "team_id": String,
        "name": String,
        "created_date": String,
        "ranking": Int64,
        "total_winnings": Int64,
        "members": List(
            Struct(
                {
                    "player_id": String,
                    "username": String,
                    "account_details": Struct(
                        {
                            "email": String,
                            "registration_date": String,
                            "premium_status": Boolean,
                            "country": String,
                            "language": String,
                        }
                    ),
                    "stats": Struct(
                        {
                            "level": Int64,
                            "experience": Int64,
                            "total_matches": Int64,
                            "win_rate": Float64,
                            "playtime_hours": Int64,
                            "achievements_completed": Int64,
                        }
                    ),
                    "inventory": Struct(
                        {
                            "currency": Struct({"premium": Int64, "standard": Int64}),
                            "items": List(
                                Struct(
                                    {
                                        "item_id": String,
                                        "name": String,
                                        "type": String,
                                        "rarity": String,
                                        "level_requirement": Int64,
                                        "stats": Struct(
                                            {
                                                "attack": Int64,
                                                "defense": Int64,
                                                "magic": Int64,
                                                "speed": Int64,
                                            }
                                        ),
                                    }
                                )
                            ),
                        }
                    ),
                    "achievements": List(
                        Struct(
                            {
                                "id": String,
                                "name": String,
                                "difficulty": String,
                                "completion_rate": Float64,
                                "points": Int64,
                                "date": String,
                            }
                        )
                    ),
                    "recent_matches": List(
                        Struct(
                            {
                                "match_id": String,
                                "game_mode": String,
                                "map": String,
                                "duration_minutes": Int64,
                                "date": String,
                                "stats": Struct(
                                    {
                                        "kills": Int64,
                                        "deaths": Int64,
                                        "assists": Int64,
                                        "damage_dealt": Int64,
                                        "healing_done": Int64,
                                        "accuracy": Float64,
                                        "headshot_percentage": Float64,
                                        "objectives_completed": Int64,
                                    }
                                ),
                                "rewards": Struct(
                                    {
                                        "experience": Int64,
                                        "currency": Int64,
                                        "items_dropped": List(
                                            Struct(
                                                {
                                                    "item_id": String,
                                                    "name": String,
                                                    "rarity": String,
                                                    "value": Int64,
                                                }
                                            )
                                        ),
                                    }
                                ),
                            }
                        )
                    ),
                }
            )
        ),
        "tournament_history": List(
            Struct(
                {
                    "tournament_id": String,
                    "name": String,
                    "placement": Int64,
                    "prize_money": Int64,
                    "matches_played": Int64,
                }
            )
        ),
    }
)

## Read LazyFrame 
(No execution triggered, data is loaded lazily aka. dag generation, like in spark)

In [5]:
lf: pl.LazyFrame = pl.scan_ndjson(
    FAKE_GAMING_DATA_DIR / "data.json",
    schema=schema,
)

In [6]:
lf.explain(optimized=True)

'NDJson SCAN [/Users/jakubpluta/Repositories/priv/polars-internals/data/fake_gaming_data/data.json]\nPROJECT */7 COLUMNS'

In [7]:
sample = lf.limit(5).collect(
    streaming=True
)  # read only 5 records. LazyFrame materialized into DataFrame

In [8]:
sample.head(1)

shape: (1, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ list[struct[ ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆ 7]]          ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ [{"f16ba9c0- ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ f9ea-4079-b2 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 06-a8e…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [9]:
sample.schema

Schema([('team_id', String),
        ('name', String),
        ('created_date', String),
        ('ranking', Int64),
        ('total_winnings', Int64),
        ('members',
         List(Struct({'player_id': String, 'username': String, 'account_details': Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}), 'stats': Struct({'level': Int64, 'experience': Int64, 'total_matches': Int64, 'win_rate': Float64, 'playtime_hours': Int64, 'achievements_completed': Int64}), 'inventory': Struct({'currency': Struct({'premium': Int64, 'standard': Int64}), 'items': List(Struct({'item_id': String, 'name': String, 'type': String, 'rarity': String, 'level_requirement': Int64, 'stats': Struct({'attack': Int64, 'defense': Int64, 'magic': Int64, 'speed': Int64})}))}), 'achievements': List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})), 'recent_matches': List(Struct({'match_id': String, 'game_mode': String, 'map': String, 'duration_minutes': Int64, 'date': String, 'stats': Struct({'kills': Int64, 'deaths': Int64, 'assists': Int64, 'damage_dealt': Int64, 'healing_done': Int64, 'accuracy': Float64, 'headshot_percentage': Float64, 'objectives_completed': Int64}), 'rewards': Struct({'experience': Int64, 'currency': Int64, 'items_dropped': List(Struct({'item_id': String, 'name': String, 'rarity': String, 'value': Int64}))})}))}))),
        ('tournament_history',
         List(Struct({'tournament_id': String, 'name': String, 'placement': Int64, 'prize_money': Int64, 'matches_played': Int64})))])

In [10]:
sample.dtypes

[String,
 String,
 String,
 Int64,
 Int64,
 List(Struct({'player_id': String, 'username': String, 'account_details': Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}), 'stats': Struct({'level': Int64, 'experience': Int64, 'total_matches': Int64, 'win_rate': Float64, 'playtime_hours': Int64, 'achievements_completed': Int64}), 'inventory': Struct({'currency': Struct({'premium': Int64, 'standard': Int64}), 'items': List(Struct({'item_id': String, 'name': String, 'type': String, 'rarity': String, 'level_requirement': Int64, 'stats': Struct({'attack': Int64, 'defense': Int64, 'magic': Int64, 'speed': Int64})}))}), 'achievements': List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})), 'recent_matches': List(Struct({'match_id': String, 'game_mode': String, 'map': String, 'duration_minutes': Int64, 'date': String, 'stats': Struct({'kills': Int64, 'deaths': Int64, 'assists': Int64, 'damage_dealt': Int64, 'healing_done': Int64, 'accuracy': Float64, 'headshot_percentage': Float64, 'objectives_completed': Int64}), 'rewards': Struct({'experience': Int64, 'currency': Int64, 'items_dropped': List(Struct({'item_id': String, 'name': String, 'rarity': String, 'value': Int64}))})}))})),
 List(Struct({'tournament_id': String, 'name': String, 'placement': Int64, 'prize_money': Int64, 'matches_played': Int64}))]

In [11]:
df = lf.collect()  # load whole data into memory

In [12]:
df.shape  # 14701 records, 7 columns

(14701, 7)

In [13]:
df.head(1)

shape: (1, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ list[struct[ ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆ 7]]          ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ [{"f16ba9c0- ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ f9ea-4079-b2 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 06-a8e…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [17]:
### members, tournament_history  is a list of structs, we can explode them into multi rows

In [14]:
df_members_exploded = df.explode(pl.col("members"))

In [15]:
df_members_exploded.head()

shape: (5, 7)
┌──────────────┬──────────────┬──────────────┬─────────┬──────────────┬──────────────┬─────────────┐
│ team_id      ┆ name         ┆ created_date ┆ ranking ┆ total_winnin ┆ members      ┆ tournament_ │
│ ---          ┆ ---          ┆ ---          ┆ ---     ┆ gs           ┆ ---          ┆ history     │
│ str          ┆ str          ┆ str          ┆ i64     ┆ ---          ┆ struct[7]    ┆ ---         │
│              ┆              ┆              ┆         ┆ i64          ┆              ┆ list[struct │
│              ┆              ┆              ┆         ┆              ┆              ┆ [5]]        │
╞══════════════╪══════════════╪══════════════╪═════════╪══════════════╪══════════════╪═════════════╡
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"f16ba9c0-f ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 9ea-4079-b20 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 6-a8e0…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"f3c264e6-6 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ b6c-4542-a13 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 3-380b…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"3ca0008c-f ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 50c-4afa-81d ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 4-86fb…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"dc4b5442-2 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ daf-452b-8de ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 9-7e21…      ┆ 8e23-06f…   │
│ 3d11adbe-36d ┆ Squad        ┆ 2024-11-22   ┆ 493     ┆ 498804       ┆ {"b81d68ff-4 ┆ [{"33b25f51 │
│ 0-4af4-9ac1- ┆ Johnson Inc  ┆              ┆         ┆              ┆ 1dd-4532-9b8 ┆ -088d-4014- │
│ 194ef7…      ┆              ┆              ┆         ┆              ┆ 0-98bd…      ┆ 8e23-06f…   │
└──────────────┴──────────────┴──────────────┴─────────┴──────────────┴──────────────┴─────────────┘

In [16]:
df_members_exploded.shape  # we exploded from 14701 -> 110613 records

(110613, 7)

In [21]:
### We can also spread (unnest) struct into multiple columns

In [17]:
df_members_exploded_spread = df_members_exploded.unnest("members")

In [18]:
df_members_exploded_spread.head(1)

shape: (1, 13)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ team_id    ┆ name      ┆ created_d ┆ ranking ┆ … ┆ inventory ┆ achieveme ┆ recent_ma ┆ tournamen │
│ ---        ┆ ---       ┆ ate       ┆ ---     ┆   ┆ ---       ┆ nts       ┆ tches     ┆ t_history │
│ str        ┆ str       ┆ ---       ┆ i64     ┆   ┆ struct[2] ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆ str       ┆         ┆   ┆           ┆ list[stru ┆ list[stru ┆ list[stru │
│            ┆           ┆           ┆         ┆   ┆           ┆ ct[6]]    ┆ ct[7]]    ┆ ct[5]]    │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3d11adbe-3 ┆ Squad     ┆ 2024-11-2 ┆ 493     ┆ … ┆ {{5067,85 ┆ [{"5695d5 ┆ [{"7f06e1 ┆ [{"33b25f │
│ 6d0-4af4-9 ┆ Johnson   ┆ 2         ┆         ┆   ┆ 179},[{"9 ┆ 38-f8c2-4 ┆ 44-0d2c-4 ┆ 51-088d-4 │
│ ac1-194ef7 ┆ Inc       ┆           ┆         ┆   ┆ 0f6348c-3 ┆ 62e-b90b- ┆ 39f-9c98- ┆ 014-8e23- │
│ …          ┆           ┆           ┆         ┆   ┆ f55…      ┆ 269…      ┆ 7a0…      ┆ 06f…      │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [19]:
df_members_exploded_spread.shape

(110613, 13)

In [25]:
### we can now access elements from structs

In [20]:
df_members_exploded_spread.select("account_details").schema

Schema([('account_details',
         Struct({'email': String, 'registration_date': String, 'premium_status': Boolean, 'country': String, 'language': String}))])

In [21]:
# extract 2 fileds from struct
df_members_exploded_spread.select(
    pl.col("account_details").struct["country"],
    pl.col("account_details").struct["premium_status"],
)

shape: (110_613, 2)
┌─────────────────────────────────┬────────────────┐
│ country                         ┆ premium_status │
│ ---                             ┆ ---            │
│ str                             ┆ bool           │
╞═════════════════════════════════╪════════════════╡
│ Gibraltar                       ┆ true           │
│ Romania                         ┆ true           │
│ Egypt                           ┆ true           │
│ Malta                           ┆ false          │
│ Antarctica (the territory Sout… ┆ true           │
│ …                               ┆ …              │
│ Mali                            ┆ false          │
│ New Zealand                     ┆ true           │
│ Burundi                         ┆ false          │
│ United States Minor Outlying I… ┆ false          │
│ Cote d'Ivoire                   ┆ true           │
└─────────────────────────────────┴────────────────┘

In [22]:
# extract filed from list
df_members_exploded_spread.select("achievements").schema

Schema([('achievements',
         List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})))])

In [23]:
df_members_exploded_spread.select("achievements").head(1)

shape: (1, 1)
┌─────────────────────────────────┐
│ achievements                    │
│ ---                             │
│ list[struct[6]]                 │
╞═════════════════════════════════╡
│ [{"5695d538-f8c2-462e-b90b-269… │
└─────────────────────────────────┘

In [24]:
df_members_exploded_spread.select(pl.col("achievements").list.get(0)).head(
    1
)  # first element from list

shape: (1, 1)
┌─────────────────────────────────┐
│ achievements                    │
│ ---                             │
│ struct[6]                       │
╞═════════════════════════════════╡
│ {"5695d538-f8c2-462e-b90b-269c… │
└─────────────────────────────────┘

In [25]:
df_members_exploded_spread.select(
    pl.col("achievements").list.eval(pl.element().struct["points"])
)  # extract field from list of structs

shape: (110_613, 1)
┌───────────────────┐
│ achievements      │
│ ---               │
│ list[i64]         │
╞═══════════════════╡
│ [662, 847, … 729] │
│ [695, 559, … 562] │
│ [339, 179, … 370] │
│ [462, 52, … 780]  │
│ [293, 23, … 218]  │
│ …                 │
│ [525, 107, … 871] │
│ [513, 863, … 736] │
│ [525, 681, … 410] │
│ [630, 556, … 867] │
│ [145, 264, … 595] │
└───────────────────┘

In [26]:
df_members_exploded_spread.select(
    pl.col("achievements").list.eval(pl.element().struct["points"]).list.mean()
)  # calculate mean points

shape: (110_613, 1)
┌──────────────┐
│ achievements │
│ ---          │
│ f64          │
╞══════════════╡
│ 490.875      │
│ 544.090909   │
│ 461.222222   │
│ 442.25       │
│ 435.833333   │
│ …            │
│ 502.0        │
│ 578.75       │
│ 656.5        │
│ 658.375      │
│ 491.785714   │
└──────────────┘

In [27]:
df_members_exploded_spread.select(pl.col("achievements")).explode(
    pl.col("achievements")
).unnest("achievements")

shape: (1_383_216, 6)
┌──────────────────────┬──────────────────────┬────────────┬─────────────────┬────────┬────────────┐
│ id                   ┆ name                 ┆ difficulty ┆ completion_rate ┆ points ┆ date       │
│ ---                  ┆ ---                  ┆ ---        ┆ ---             ┆ ---    ┆ ---        │
│ str                  ┆ str                  ┆ str        ┆ f64             ┆ i64    ┆ str        │
╞══════════════════════╪══════════════════════╪════════════╪═════════════════╪════════╪════════════╡
│ 5695d538-f8c2-462e-b ┆ Ultimate Boss Slayer ┆ Extreme    ┆ 45.57           ┆ 662    ┆ 2024-12-28 │
│ 90b-269c93…          ┆                      ┆            ┆                 ┆        ┆            │
│ 59e568e5-4f56-492d-8 ┆ 100% Completion      ┆ Medium     ┆ 24.42           ┆ 847    ┆ 2025-01-13 │
│ e21-100193…          ┆                      ┆            ┆                 ┆        ┆            │
│ c26f4010-0162-4e96-9 ┆ Speed Runner         ┆ Extreme    ┆ 56.01           ┆ 109    ┆ 2025-01-09 │
│ 497-d0f651…          ┆                      ┆            ┆                 ┆        ┆            │
│ c187c0e0-231f-4ef4-b ┆ Master of Combat     ┆ Extreme    ┆ 31.29           ┆ 836    ┆ 2024-11-14 │
│ 5c3-2e9216…          ┆                      ┆            ┆                 ┆        ┆            │
│ 451377a4-498b-4fbc-8 ┆ Speed Runner         ┆ Hard       ┆ 97.69           ┆ 277    ┆ 2025-01-04 │
│ 405-82f4d3…          ┆                      ┆            ┆                 ┆        ┆            │
│ …                    ┆ …                    ┆ …          ┆ …               ┆ …      ┆ …          │
│ 821baf37-9aee-481f-9 ┆ 100% Completion      ┆ Hard       ┆ 82.26           ┆ 755    ┆ 2024-12-19 │
│ b6f-c17456…          ┆                      ┆            ┆                 ┆        ┆            │
│ d1fd0e35-69b3-4457-8 ┆ Speed Runner         ┆ Medium     ┆ 57.41           ┆ 47     ┆ 2024-12-31 │
│ 57d-5cecc7…          ┆                      ┆            ┆                 ┆        ┆            │
│ d409dce4-439c-4e6c-b ┆ Master of Combat     ┆ Easy       ┆ 94.94           ┆ 650    ┆ 2024-12-25 │
│ bfb-3fec15…          ┆                      ┆            ┆                 ┆        ┆            │
│ 737316ab-866d-41ae-b ┆ Hidden Treasure      ┆ Medium     ┆ 24.04           ┆ 998    ┆ 2024-12-27 │
│ 8ee-7ad35b…          ┆                      ┆            ┆                 ┆        ┆            │
│ 3d7e6d0d-84e7-4c4d-b ┆ Master of Combat     ┆ Easy       ┆ 32.21           ┆ 595    ┆ 2025-01-25 │
│ 871-f5aaa6…          ┆                      ┆            ┆                 ┆        ┆            │
└──────────────────────┴──────────────────────┴────────────┴─────────────────┴────────┴────────────┘

In [ ]:
df_members_exploded_spread.select("team_id", "player_id", "achievements").explode(
    pl.col("achievements")
).unnest("achievements").group_by("team_id", "player_id").agg(
    pl.col("completion_rate").mean().alias("avg_player_completion_rate"),
    pl.col("points").mean().alias("avg_player_points"),
)

shape: (110_613, 4)
┌──────────────────────────┬─────────────────────────┬─────────────────────────┬───────────────────┐
│ team_id                  ┆ player_id               ┆ avg_player_completion_r ┆ avg_player_points │
│ ---                      ┆ ---                     ┆ ate                     ┆ ---               │
│ str                      ┆ str                     ┆ ---                     ┆ f64               │
│                          ┆                         ┆ f64                     ┆                   │
╞══════════════════════════╪═════════════════════════╪═════════════════════════╪═══════════════════╡
│ 7189d435-5b2d-4655-8338- ┆ 4143f423-d7b7-4d82-b68e ┆ 44.590625               ┆ 560.375           │
│ 8bab82…                  ┆ -758e83…                ┆                         ┆                   │
│ 095558bd-83c6-4254-9b81- ┆ 736cd0c6-628d-42d8-b61d ┆ 63.263                  ┆ 373.8             │
│ 5f06c7…                  ┆ -d7b978…                ┆                         ┆                   │
│ 0fd13772-afd5-41fd-b694- ┆ ca3b4611-1f89-46d0-9b2e ┆ 52.713333               ┆ 528.5             │
│ 60ce22…                  ┆ -fda51f…                ┆                         ┆                   │
│ 3debf016-19d6-4e98-b4fc- ┆ ebf2d783-6cf6-4930-bf57 ┆ 41.27375                ┆ 593.5             │
│ 74be2e…                  ┆ -119f8b…                ┆                         ┆                   │
│ b69d1787-5f42-4aa9-bb24- ┆ 62c7dcf9-84e9-4dea-b4e1 ┆ 47.456316               ┆ 446.736842        │
│ a79320…                  ┆ -c1d806…                ┆                         ┆                   │
│ …                        ┆ …                       ┆ …                       ┆ …                 │
│ 35b8550e-0210-4088-8217- ┆ e4cdb1bf-f596-4a30-b901 ┆ 44.204                  ┆ 448.0             │
│ f30b75…                  ┆ -b42e2f…                ┆                         ┆                   │
│ 885ad80d-9e91-4441-927a- ┆ d76d9df7-17d9-4ddf-b8c5 ┆ 50.925625               ┆ 421.1875          │
│ 32de04…                  ┆ -b4bc45…                ┆                         ┆                   │
│ e46ecb38-560f-41bf-b96b- ┆ e0f4af1b-2265-4d2e-8a16 ┆ 56.056471               ┆ 511.647059        │
│ c75650…                  ┆ -682b40…                ┆                         ┆                   │
│ 71d8069b-6369-4a2b-9165- ┆ fe2b8468-fcc2-4772-a07a ┆ 41.729412               ┆ 485.529412        │
│ f94c17…                  ┆ -90cdef…                ┆                         ┆                   │
│ e955225d-5697-48dc-9937- ┆ d62bb540-e524-4ffa-a786 ┆ 49.84                   ┆ 441.916667        │
│ b54d09…                  ┆ -fcbf7f…                ┆                         ┆                   │
└──────────────────────────┴─────────────────────────┴─────────────────────────┴───────────────────┘

In [42]:
df_members_exploded_spread.select(
    pl.col("team_id"), pl.col("player_id"), pl.col("stats")
).unnest("stats")

shape: (110_613, 8)
┌─────────────┬─────────────┬───────┬────────────┬────────────┬──────────┬────────────┬────────────┐
│ team_id     ┆ player_id   ┆ level ┆ experience ┆ total_matc ┆ win_rate ┆ playtime_h ┆ achievemen │
│ ---         ┆ ---         ┆ ---   ┆ ---        ┆ hes        ┆ ---      ┆ ours       ┆ ts_complet │
│ str         ┆ str         ┆ i64   ┆ i64        ┆ ---        ┆ f64      ┆ ---        ┆ ed         │
│             ┆             ┆       ┆            ┆ i64        ┆          ┆ i64        ┆ ---        │
│             ┆             ┆       ┆            ┆            ┆          ┆            ┆ i64        │
╞═════════════╪═════════════╪═══════╪════════════╪════════════╪══════════╪════════════╪════════════╡
│ 3d11adbe-36 ┆ f16ba9c0-f9 ┆ 91    ┆ 159523     ┆ 313        ┆ 50.35    ┆ 1173       ┆ 32         │
│ d0-4af4-9ac ┆ ea-4079-b20 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 1-194ef7…   ┆ 6-a8e0b7…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3d11adbe-36 ┆ f3c264e6-6b ┆ 7     ┆ 13223      ┆ 609        ┆ 53.76    ┆ 4778       ┆ 67         │
│ d0-4af4-9ac ┆ 6c-4542-a13 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 1-194ef7…   ┆ 3-380b53…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3d11adbe-36 ┆ 3ca0008c-f5 ┆ 81    ┆ 160299     ┆ 710        ┆ 60.64    ┆ 4647       ┆ 10         │
│ d0-4af4-9ac ┆ 0c-4afa-81d ┆       ┆            ┆            ┆          ┆            ┆            │
│ 1-194ef7…   ┆ 4-86fbae…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3d11adbe-36 ┆ dc4b5442-2d ┆ 41    ┆ 47191      ┆ 225        ┆ 49.86    ┆ 1274       ┆ 25         │
│ d0-4af4-9ac ┆ af-452b-8de ┆       ┆            ┆            ┆          ┆            ┆            │
│ 1-194ef7…   ┆ 9-7e217c…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3d11adbe-36 ┆ b81d68ff-41 ┆ 19    ┆ 22781      ┆ 549        ┆ 54.27    ┆ 879        ┆ 42         │
│ d0-4af4-9ac ┆ dd-4532-9b8 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 1-194ef7…   ┆ 0-98bd5f…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ …           ┆ …           ┆ …     ┆ …          ┆ …          ┆ …        ┆ …          ┆ …          │
│ 3b10d6b9-f1 ┆ 49072ac3-92 ┆ 77    ┆ 84700      ┆ 324        ┆ 46.04    ┆ 2769       ┆ 66         │
│ 27-4945-b1d ┆ 5a-4fe8-877 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3-202c51…   ┆ f-35edfd…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3b10d6b9-f1 ┆ 7d233f9e-ff ┆ 20    ┆ 30340      ┆ 514        ┆ 42.26    ┆ 3583       ┆ 51         │
│ 27-4945-b1d ┆ 70-4bec-9c2 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3-202c51…   ┆ 9-9831ce…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3b10d6b9-f1 ┆ a4353426-9b ┆ 30    ┆ 45990      ┆ 126        ┆ 49.89    ┆ 3306       ┆ 95         │
│ 27-4945-b1d ┆ ac-4a61-86b ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3-202c51…   ┆ 4-6a1567…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3b10d6b9-f1 ┆ 42a7f7dd-e0 ┆ 20    ┆ 21040      ┆ 703        ┆ 57.74    ┆ 3861       ┆ 58         │
│ 27-4945-b1d ┆ 8d-4f7e-85a ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3-202c51…   ┆ c-3d5291…   ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3b10d6b9-f1 ┆ 543af766-5e ┆ 31    ┆ 51026      ┆ 998        ┆ 52.28    ┆ 4218       ┆ 96         │
│ 27-4945-b1d ┆ d2-4063-9c1 ┆       ┆            ┆            ┆          ┆            ┆            │
│ 3-202c51…   ┆ 8-051729…   ┆       ┆            ┆            ┆          ┆            ┆            │
└─────────────┴─────────────┴───────┴────────────┴────────────┴──────────┴────────────┴────────────┘

In [44]:
df_members_exploded_spread.head(1)

shape: (1, 13)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ team_id    ┆ name      ┆ created_d ┆ ranking ┆ … ┆ inventory ┆ achieveme ┆ recent_ma ┆ tournamen │
│ ---        ┆ ---       ┆ ate       ┆ ---     ┆   ┆ ---       ┆ nts       ┆ tches     ┆ t_history │
│ str        ┆ str       ┆ ---       ┆ i64     ┆   ┆ struct[2] ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆ str       ┆         ┆   ┆           ┆ list[stru ┆ list[stru ┆ list[stru │
│            ┆           ┆           ┆         ┆   ┆           ┆ ct[6]]    ┆ ct[7]]    ┆ ct[5]]    │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3d11adbe-3 ┆ Squad     ┆ 2024-11-2 ┆ 493     ┆ … ┆ {{5067,85 ┆ [{"5695d5 ┆ [{"7f06e1 ┆ [{"33b25f │
│ 6d0-4af4-9 ┆ Johnson   ┆ 2         ┆         ┆   ┆ 179},[{"9 ┆ 38-f8c2-4 ┆ 44-0d2c-4 ┆ 51-088d-4 │
│ ac1-194ef7 ┆ Inc       ┆           ┆         ┆   ┆ 0f6348c-3 ┆ 62e-b90b- ┆ 39f-9c98- ┆ 014-8e23- │
│ …          ┆           ┆           ┆         ┆   ┆ f55…      ┆ 269…      ┆ 7a0…      ┆ 06f…      │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [70]:
df_users = df_members_exploded_spread.select(
    pl.col("team_id"),
    pl.col("player_id"),
    pl.col("username"),
    pl.col("account_details"),
    pl.col("achievements"),
    pl.col("stats"),
)

In [74]:
df_members_exploded_spread.select("achievements").schema

Schema([('achievements',
         List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})))])

In [71]:
df_users.head()

shape: (5, 6)
┌────────────────┬────────────────┬───────────────┬────────────────┬───────────────┬───────────────┐
│ team_id        ┆ player_id      ┆ username      ┆ account_detail ┆ achievements  ┆ stats         │
│ ---            ┆ ---            ┆ ---           ┆ s              ┆ ---           ┆ ---           │
│ str            ┆ str            ┆ str           ┆ ---            ┆ list[struct[6 ┆ struct[6]     │
│                ┆                ┆               ┆ struct[5]      ┆ ]]            ┆               │
╞════════════════╪════════════════╪═══════════════╪════════════════╪═══════════════╪═══════════════╡
│ 3d11adbe-36d0- ┆ f16ba9c0-f9ea- ┆ marvinthomas  ┆ {"kevin49@exam ┆ [{"5695d538-f ┆ {91,159523,31 │
│ 4af4-9ac1-194e ┆ 4079-b206-a8e0 ┆               ┆ ple.com","2025 ┆ 8c2-462e-b90b ┆ 3,50.35,1173, │
│ f7…            ┆ b7…            ┆               ┆ -0…            ┆ -269…         ┆ 32}           │
│ 3d11adbe-36d0- ┆ f3c264e6-6b6c- ┆ moniquelowery ┆ {"joel28@examp ┆ [{"5f98e39f-4 ┆ {7,13223,609, │
│ 4af4-9ac1-194e ┆ 4542-a133-380b ┆               ┆ le.net","2024- ┆ 1af-45f3-b433 ┆ 53.76,4778,67 │
│ f7…            ┆ 53…            ┆               ┆ 12…            ┆ -21c…         ┆ }             │
│ 3d11adbe-36d0- ┆ 3ca0008c-f50c- ┆ uroberson     ┆ {"osborntimoth ┆ [{"b72b2382-b ┆ {81,160299,71 │
│ 4af4-9ac1-194e ┆ 4afa-81d4-86fb ┆               ┆ y@example.com" ┆ 630-42eb-b5c2 ┆ 0,60.64,4647, │
│ f7…            ┆ ae…            ┆               ┆ ,"…            ┆ -5cc…         ┆ 10}           │
│ 3d11adbe-36d0- ┆ dc4b5442-2daf- ┆ wellis        ┆ {"lindsay48@ex ┆ [{"319de773-6 ┆ {41,47191,225 │
│ 4af4-9ac1-194e ┆ 452b-8de9-7e21 ┆               ┆ ample.com","20 ┆ 36a-4841-bd7a ┆ ,49.86,1274,2 │
│ f7…            ┆ 7c…            ┆               ┆ 24…            ┆ -304…         ┆ 5}            │
│ 3d11adbe-36d0- ┆ b81d68ff-41dd- ┆ robinsonlaura ┆ {"gary69@examp ┆ [{"332f7833-6 ┆ {19,22781,549 │
│ 4af4-9ac1-194e ┆ 4532-9b80-98bd ┆               ┆ le.net","2025- ┆ 662-48cc-b24a ┆ ,54.27,879,42 │
│ f7…            ┆ 5f…            ┆               ┆ 01…            ┆ -25c…         ┆ }             │
└────────────────┴────────────────┴───────────────┴────────────────┴───────────────┴───────────────┘

In [72]:
df_users.explode(pl.col("achievements")).unnest("achievements").unnest(
    "account_details"
).unnest("stats").head(1)

shape: (1, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ team_id   ┆ player_id ┆ username  ┆ email     ┆ … ┆ total_mat ┆ win_rate ┆ playtime_ ┆ achieveme │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ches      ┆ ---      ┆ hours     ┆ nts_compl │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ f64      ┆ ---       ┆ eted      │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆          ┆ i64       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆ i64       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 3d11adbe- ┆ f16ba9c0- ┆ marvintho ┆ kevin49@e ┆ … ┆ 313       ┆ 50.35    ┆ 1173      ┆ 32        │
│ 36d0-4af4 ┆ f9ea-4079 ┆ mas       ┆ xample.co ┆   ┆           ┆          ┆           ┆           │
│ -9ac1-194 ┆ -b206-a8e ┆           ┆ m         ┆   ┆           ┆          ┆           ┆           │
│ ef7…      ┆ 0b7…      ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [ ]:
# Schema([('achievements', List(Struct({'id': String, 'name': String, 'difficulty': String, 'completion_rate': Float64, 'points': Int64, 'date': String})))])


df_users_agg = (
    df_users.explode(pl.col("achievements"))
    .unnest("achievements")
    .unnest("account_details")
    .unnest("stats")
    .select(
        pl.col("team_id"),
        pl.col("player_id"),
        pl.col("username"),
        pl.col("email"),
        pl.col("registration_date").str.to_date("%Y-%m-%d"),
        (datetime.date.today() - pl.col("registration_date").str.to_date("%Y-%m-%d"))
        .dt.total_days()
        .cast(pl.Int64)
        .alias("player_days_since_registration"),
        pl.when(pl.col("premium_status").eq(True))
        .then(1)
        .otherwise(0)
        .alias("is_player_premium"),
        pl.col("premium_status"),
        pl.col("country").alias("player_country"),
        pl.col("language").alias("player_language"),
        pl.col("level").alias("player_level"),
        pl.col("experience").alias("player_experience"),
        pl.col("total_matches").alias("player_total_matches"),
        pl.col("win_rate").alias("player_win_rate"),
        pl.col("playtime_hours").alias("player_playtime_hours"),
        pl.col("achievements_completed").alias("player_achievements_completed"),
        pl.col("date").alias("player_achievement_date"),
        pl.col("points").alias("player_achievement_points"),
        pl.col("completion_rate").alias("player_achievement_completion_rate"),
        pl.col("difficulty").alias("player_achievement_difficulty"),
    )
    .group_by(
        "team_id",
        "player_id",
        "username",
        "email",
        "registration_date",
        "player_days_since_registration",
        "is_player_premium",
        "premium_status",
        "player_country",
        "player_language",
        "player_level",
        "player_experience",
        "player_total_matches",
        "player_win_rate",
        "player_playtime_hours",
        "player_achievements_completed",
    )
    .agg(
        pl.col("player_achievement_date").max().alias("player_last_achievement_date"),
        pl.col("player_achievement_points")
        .mean()
        .alias("player_avg_achievement_points"),
        pl.col("player_achievement_completion_rate")
        .mean()
        .alias("player_avg_achievement_completion_rate"),
        pl.col("player_achievement_difficulty")
        .value_counts(sort=True)
        .first()
        .struct["player_achievement_difficulty"]
        .alias("player_achievement_most_common_difficulty"),
    )
)

In [133]:
df_users_agg.head()

shape: (5, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team_id   ┆ player_id ┆ username  ┆ email     ┆ … ┆ player_la ┆ player_av ┆ player_av ┆ player_a │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ st_achiev ┆ g_achieve ┆ g_achieve ┆ chieveme │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ement_dat ┆ ment_poin ┆ ment_comp ┆ nt_most_ │
│           ┆           ┆           ┆           ┆   ┆ e         ┆ ts        ┆ let…      ┆ common…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ f64       ┆ f64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 71705a03- ┆ 631df60a- ┆ nmorris   ┆ mdiaz@exa ┆ … ┆ 2025-01-2 ┆ 527.63636 ┆ 66.512727 ┆ Medium   │
│ 9a48-4d47 ┆ da9d-464c ┆           ┆ mple.org  ┆   ┆ 2         ┆ 4         ┆           ┆          │
│ -801a-51c ┆ -9d7d-212 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 16a…      ┆ c8d…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e3af9675- ┆ 5ae52b69- ┆ blanchard ┆ michael96 ┆ … ┆ 2025-01-1 ┆ 464.2     ┆ 68.698    ┆ Extreme  │
│ 5506-4e83 ┆ 887f-40c0 ┆ matthew   ┆ @example. ┆   ┆ 2         ┆           ┆           ┆          │
│ -b7cc-bdc ┆ -8e7f-c80 ┆           ┆ org       ┆   ┆           ┆           ┆           ┆          │
│ 378…      ┆ 072…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5a4e99ca- ┆ 28c1030f- ┆ sarah26   ┆ ohensley@ ┆ … ┆ 2025-01-1 ┆ 485.33333 ┆ 47.008333 ┆ Easy     │
│ aa03-4005 ┆ e2e0-4a9b ┆           ┆ example.c ┆   ┆ 2         ┆ 3         ┆           ┆          │
│ -94e4-caa ┆ -bb4e-d5b ┆           ┆ om        ┆   ┆           ┆           ┆           ┆          │
│ 712…      ┆ 2ba…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a284cb02- ┆ 9815c1ce- ┆ sstevens  ┆ glovermon ┆ … ┆ 2025-01-2 ┆ 508.06666 ┆ 67.55     ┆ Easy     │
│ df84-43b4 ┆ 03a2-4c16 ┆           ┆ ica@examp ┆   ┆ 3         ┆ 7         ┆           ┆          │
│ -b953-ee0 ┆ -9fa3-e15 ┆           ┆ le.net    ┆   ┆           ┆           ┆           ┆          │
│ 861…      ┆ ca9…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ecf24194- ┆ 3a26bb7c- ┆ ichristen ┆ nicholas4 ┆ … ┆ 2025-01-0 ┆ 578.125   ┆ 43.058125 ┆ Easy     │
│ c8c3-486a ┆ 6b09-415d ┆ sen       ┆ 7@example ┆   ┆ 6         ┆           ┆           ┆          │
│ -8f59-4d9 ┆ -890e-1e5 ┆           ┆ .org      ┆   ┆           ┆           ┆           ┆          │
│ 7b0…      ┆ 970…      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [151]:
df_users_agg.group_by("team_id").agg(
    pl.col("player_id").count().alias("members_count"),
    pl.col("is_player_premium").sum().alias("members_premium_count"),
    (pl.col("is_player_premium").sum() / pl.col("player_id").count())
    .cast(pl.Float64)
    .alias("member_premium_percentage"),
    pl.col("player_days_since_registration")
    .mean()
    .cast(pl.Int64)
    .alias("member_avg_days_since_registration"),
    pl.col("player_level").mean().cast(pl.Int64).alias("member_avg_level"),
    pl.col("player_experience").mean().cast(pl.Float64).alias("member_avg_experience"),
    pl.col("player_total_matches").mean().alias("member_avg_total_matches"),
    pl.col("player_win_rate").mean().alias("member_avg_win_rate"),
    pl.col("player_playtime_hours").mean().alias("member_avg_playtime_hours"),
    pl.col("player_playtime_hours").sum().alias("member_total_playtime_hours"),
    pl.col("player_achievements_completed")
    .sum()
    .alias("member_total_achievements_completed"),
    pl.col("player_avg_achievement_points")
    .mean()
    .alias("member_avg_achievement_points"),
    pl.col("player_avg_achievement_completion_rate")
    .mean()
    .alias("member_avg_achievement_completion_rate"),
    pl.col("player_achievement_most_common_difficulty")
    .value_counts(sort=True)
    .first()
    .struct["player_achievement_most_common_difficulty"]
    .alias("member_most_common_achievement_difficulty"),
    pl.col("player_country")
    .value_counts(sort=True)
    .first()
    .struct["player_country"]
    .alias("player_country"),
    pl.col("player_language").value_counts(sort=True).first().alias("player_language"),
).head(3)

shape: (3, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ team_id   ┆ members_c ┆ members_p ┆ member_pr ┆ … ┆ member_av ┆ member_mo ┆ player_co ┆ player_l │
│ ---       ┆ ount      ┆ remium_co ┆ emium_per ┆   ┆ g_achieve ┆ st_common ┆ untry     ┆ anguage  │
│ str       ┆ ---       ┆ unt       ┆ centage   ┆   ┆ ment_comp ┆ _achievem ┆ ---       ┆ ---      │
│           ┆ u32       ┆ ---       ┆ ---       ┆   ┆ let…      ┆ ent…      ┆ struct[2] ┆ struct[2 │
│           ┆           ┆ i32       ┆ f64       ┆   ┆ ---       ┆ ---       ┆           ┆ ]        │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7547918a- ┆ 5         ┆ 2         ┆ 0.4       ┆ … ┆ 50.674545 ┆ Easy      ┆ {"Mayotte ┆ {"ja",2} │
│ 4668-47b7 ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1}      ┆          │
│ -83ca-774 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 367…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0e56b981- ┆ 6         ┆ 2         ┆ 0.333333  ┆ … ┆ 51.270511 ┆ Hard      ┆ {"Ireland ┆ {"fr",3} │
│ 9ef5-48ba ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1}      ┆          │
│ -8913-a64 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 55d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 17beb125- ┆ 10        ┆ 5         ┆ 0.5       ┆ … ┆ 54.106507 ┆ Easy      ┆ {"Marshal ┆ {"en",5} │
│ 9e68-42b5 ┆           ┆           ┆           ┆   ┆           ┆           ┆ l Islands ┆          │
│ -95ec-3a3 ┆           ┆           ┆           ┆   ┆           ┆           ┆ ",1}      ┆          │
│ ab6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘